name: Continuous Integration

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.2
          working-directory: ./src

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Get dependencies
        run: go get -v -t -d ./...
        working-directory: ./src 
      - name: Build project
        run: go build -v ./...
        working-directory: ./src

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test -v ./...
        working-directory: ./src
